name: CI

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 20, 17, 11 ]
        experimental: [ false ]
        # Only test on macos and windows with a single recent JDK to avoid a
        # combinatorial explosion of test configurations.
        # Most OS-specific issues are not specific to a particular JDK version.
        include:
          - os: macos-latest
            java: 20
            experimental: false
          - os: windows-latest
            java: 20
            experimental: false
          - os: ubuntu-latest
            java: 20
            experimental: false
          - os: ubuntu-latest
            java: 21-ea
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
            ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Install'
        shell: bash
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: 'Test'
        shell: bash
        run: mvn test -B
      - name: 'Test compatibility with JDK 11'
        if: ${{ matrix.java == 17 }}
        shell: bash
        run: mvn test -B -Dsurefire.jdk-toolchain-version=11
      - name: 'Javadoc'
        # only generate javadoc on JDKs with the fix for https://bugs.openjdk.org/browse/JDK-8241780
        if: ${{ matrix.java >= 15 }}
        shell: bash
        run: mvn -P '!examples' javadoc:aggregate

  publish_snapshot:
    name: 'Publish snapshot'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/error-prone' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
          server-id: ossrh
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: 'Publish'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: mvn source:jar deploy -B -DskipTests=true -Dinvoker.skip=true

  generate_docs:
    name: 'Generate latest docs'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/error-prone' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Generate latest docs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./util/generate-latest-docs.sh
